// User creation types
export const CREATE_USER_LOADING = 'CREATE/USER/LOADING';
export const CREATE_USER_SUCCESS = 'CREATE/USER/SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE/USER/FAILURE';

// User retrieval types
export const GET_USER_LOADING = 'GET/USER/LOADING';
export const GET_USER_SUCCESS = 'GET/USER/SUCCESS';
export const GET_USER_FAILURE = 'GET/USER/FAILURE';

// User update types
export const UPDATE_USER_LOADING = 'UPDATE/USER/LOADING';
export const UPDATE_USER_SUCCESS = 'UPDATE/USER/SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE/USER/FAILURE';

// User deletion types
export const DELETE_USER_LOADING = 'DELETE/USER/LOADING';
export const DELETE_USER_SUCCESS = 'DELETE/USER/SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE/USER/FAILURE';

// User analytics types
export const GET_USER_ANALYTICS_LOADING = 'GET/USER/ANALYTICS/LOADING';
export const GET_USER_ANALYTICS_SUCCESS = 'GET/USER/ANALYTICS/SUCCESS';
export const GET_USER_ANALYTICS_FAILURE = 'GET/USER/ANALYTICS/FAILURE';

// Top active users analytics types
export const GET_TOP_ACTIVE_USERS_LOADING = 'GET/TOP/ACTIVE/USERS/LOADING';
export const GET_TOP_ACTIVE_USERS_SUCCESS = 'GET/TOP/ACTIVE/USERS/SUCCESS';
export const GET_TOP_ACTIVE_USERS_FAILURE = 'GET/TOP/ACTIVE/USERS/FAILURE';
